environment:

  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python38"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: "64"

  global:
    POETRY_PYPI_TOKEN_PYPI:
      secure: uvO05h1Fbx/RYMGq5YMoiWJTp3JkuRbDqnm3VkINHpcUn9BcXRB/e4/aMKuucWFcwUZNpw+9BB5uO6DenpBcQIX1ET/fwoRTcRCRY7E97PKEvvBR29MjpHqX2UkdDCOqyEaNl/KenU9IWdVIDe3PgTYofgha+q2zO/It1LQzVg9L10x6oH0/tMyGz009FUTo+k+CA+VvAx3BJqV3p59b2HARdDVTWuv2UGg9swfDWXd0OPbaFP+iSzEyKBgPclXSfRhB00PlfHK/9PtPQyqMag==

matrix:
  fast_finish: true

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --upgrade pip"

  # Install wheel for faster installs
  - "python -m pip install --upgrade wheel"

  # Install poetry
  - "python -m pip install poetry"

  # Install test dependencies
  - "poetry install --only=test"

build: false

test_script:
  - "poetry run pytest --cov=pymem"

after_test:
  - "poetry run codecov -t %COV_TOKEN%"
  - "poetry install --only=doc"
  - "poetry run sphinx-apidoc -f -o docs/source pymem"
  - "cd docs/source && poetry run make.bat html"
  - "poetry build"

for:
-
  branches:
    only:
      - master

  build_script:
    - python -m pip install wheel poetry
    - poetry install
    - poetry build

  build: on

  deploy: on

  deploy_script:
    - cmd: poetry publish --verbose --skip-existing --no-interaction || exit 0

artifacts:
  - path: 'docs/source/_build/html'
    name: doc